# GUTS on YJMob-14d

The Full-Graph baseline, a GUTS source run and shard unlearning of a node forget set on YJMob-14d (K=130, seed 2026).

## Settings

Paths, GPUs, seed, forget set and run directories.

In [1]:
import json
import sys
from pathlib import Path

import pandas as pd
import yaml

REPO_ROOT = Path.cwd()
assert (REPO_ROOT / "guts").is_dir() and (REPO_ROOT / "configs").is_dir(), \
    "Start Jupyter from the repository root."
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from guts.method.utils import timestamp_id
from guts.yjmob import full_graph, pipeline
from guts.yjmob.data import preprocess
from guts.yjmob.unlearning import forget_sets, unlearn_batch, unlearn_batch_retry

In [2]:
NUM_GPUS = 4                         # GPUs for shard training and evaluation
SEED = 2026                          # run seed (partition and shard training)
CONFIG = "configs/yjmob_14d.yaml"    # K=130 and the other settings of the paper

DATASET_NAME = "dataset1"            # YJMob CSV under processed/yjmob/raw/
DATA_DIR = "processed/yjmob_1_14d"   # days 0-13
STRATA = "guts/yjmob/unlearning/strata.json"

FORGET_TYPE = "node"
FORGET_PERCENT = 0.05                # % of the train cells
FORGET_SET = f"processed/forget_sets/yjmob/Node/forget_node_seed{SEED}_{FORGET_PERCENT:g}pct.json"
CLEAN_DIR = f"processed/yjmob_1_14d_clean_node_seed{SEED}_{FORGET_PERCENT:g}pct"

RUN_ID = timestamp_id()              # new runs each time this cell runs
BASE_RUN_DIR = REPO_ROOT / "Results/runs/yjmob_14d" / f"{RUN_ID}_full_graph_seed{SEED}"
SHARD_RUN_DIR = REPO_ROOT / "Results/shard-runs/yjmob_14d" / f"{RUN_ID}_guts_k130_seed{SEED}"
UNLEARN_RUN_DIR = (REPO_ROOT / "Results/shard-unlearns/yjmob_14d"
                   / f"{RUN_ID}_guts_k130_seed{SEED}_{FORGET_TYPE}_{FORGET_PERCENT:g}pct")
for run_dir in (BASE_RUN_DIR, SHARD_RUN_DIR, UNLEARN_RUN_DIR):
    print("run directory:", run_dir.relative_to(REPO_ROOT))

run directory: Results/runs/yjmob_14d/261027_15h51m07s_full_graph_seed2026
run directory: Results/shard-runs/yjmob_14d/261027_15h51m07s_guts_k130_seed2026
run directory: Results/shard-unlearns/yjmob_14d/261027_15h51m07s_guts_k130_seed2026_node_0.05pct

## Data

The 14-day YJMob dataset, the quartile strata file, the node forget set and the clean data without it.

In [3]:
if (REPO_ROOT / DATA_DIR / "next_location_meta.json").exists():
    print("dataset exists:", DATA_DIR)
else:
    preprocess.main(["--dataset_name", DATASET_NAME, "--day_range", "0", "13",
                     "--out_name", Path(DATA_DIR).name])

if (REPO_ROOT / STRATA).exists():
    print("strata file exists:", STRATA)
else:
    forget_sets.main(["strata", "--source_dir", DATA_DIR])

dataset exists: processed/yjmob_1_14d
strata file exists: guts/yjmob/unlearning/strata.json

In [4]:
if (REPO_ROOT / STRATA).exists():
    print("strata file exists:", STRATA)
else:
    forget_sets.main(["strata", "--source_dir", DATA_DIR])

if (REPO_ROOT / FORGET_SET).exists():
    print("forget set exists:", FORGET_SET)
else:
    forget_sets.main(["batch", "--source_dir", DATA_DIR, "--percent", f"{FORGET_PERCENT:g}",
                      "--types", FORGET_TYPE, "--seed", str(SEED)])

if (REPO_ROOT / CLEAN_DIR / "next_location_meta.json").exists():
    print("clean data exists:", CLEAN_DIR)
else:
    preprocess.main(["--dataset_name", DATASET_NAME, "--day_range", "0", "13",
                     "--fixed_grid_info_from", f"{DATA_DIR}/next_location_meta.pt",
                     "--exclude_nodes_from", FORGET_SET, "--out_name", Path(CLEAN_DIR).name])

strata file exists: guts/yjmob/unlearning/strata.json
forget set exists: processed/forget_sets/yjmob/Node/forget_node_seed2026_0.05pct.json
clean data exists: processed/yjmob_1_14d_clean_node_seed2026_0.05pct

## Full-Graph baseline

One GraphSAGE + GRU model trained on the whole graph, evaluated with the shard routing evaluation of a single shard.

In [5]:
if (BASE_RUN_DIR / "results.json").exists():
    print("finished run exists:", BASE_RUN_DIR.relative_to(REPO_ROOT))
else:
    argv = ["--config", CONFIG, "--num-gpus", str(NUM_GPUS), "--seed", str(SEED)]
    if BASE_RUN_DIR.exists():
        argv += ["--resume-dir", str(BASE_RUN_DIR)]
    else:
        argv += ["--out", str(BASE_RUN_DIR.parent), "--override", f"output.run_name={BASE_RUN_DIR.name}"]
    full_graph.main(argv)

[15:51:07] Full-Graph baseline  2026-10-27  run=Results/runs/yjmob_14d/261027_15h51m07s_full_graph_seed2026  seed=2026 (given)  GPUs=4
[15:51:07]   data=processed/yjmob_1_14d  days 0-13 (14)
[15:51:07] STEP 1/3 full-graph data (one shard with every cell)
[15:51:16]   data done  14 day graphs (1,418-652,117 edges)  rolling graphs (window 3, target days 3-13)  9s
[15:51:16] STEP 2/3 training
[15:51:16]   training 1 model on 4 GPUs (torchrun data parallel)
[17:14:12]   training done  4976s
[17:14:12]   best E57/stopped E72  train time 4389s
[17:14:12]     train  MRR 0.3066  ACC@1 0.2136  ACC@5 0.4028  ACC@10 0.4885
[17:14:12]     val    MRR 0.2806  ACC@1 0.1924  ACC@5 0.3710  ACC@10 0.4530
[17:14:12] STEP 3/3 shard routing evaluation (test)
[17:14:44]   test  MRR 0.2480 ACC@1 0.1645 ACC@5 0.3315 ACC@10 0.4131  routable 99.97%  32s
[17:14:44] done  5017s  -> Results/runs/yjmob_14d/261027_15h51m07s_full_graph_seed2026/results.json

## GUTS source run

Per-day GUTS partitioning, one GraphSAGE model per shard, and shard routing evaluation on the test split.

In [6]:
if (SHARD_RUN_DIR / "results.json").exists():
    print("finished run exists:", SHARD_RUN_DIR.relative_to(REPO_ROOT))
else:
    argv = ["--config", CONFIG, "--num-gpus", str(NUM_GPUS), "--seed", str(SEED)]
    if SHARD_RUN_DIR.exists():
        argv += ["--resume-dir", str(SHARD_RUN_DIR)]
    else:
        argv += ["--override", f"output.root={SHARD_RUN_DIR.parent}", f"output.run_name={SHARD_RUN_DIR.name}"]
    pipeline.main(argv)

[17:14:44] GUTS pipeline  2026-10-27  run=Results/shard-runs/yjmob_14d/261027_15h51m07s_guts_k130_seed2026  seed=2026 (given)  K=130  GPUs=4
[17:14:44]   data=processed/yjmob_1_14d  days 0-13 (14)
[17:14:44] STEP 1/3 partition (14 days, K=130)
[17:14:44]   partition fit: 14 days on 8 worker processes
[17:19:40]   partition fit done  296s
[17:20:32]   subgraph assignment done  14/14 days  52s
[17:20:32]   partition done  mean over 14 days: shards/traj 2.602  cstr 0.462  348s
[17:20:32] STEP 2/3 shard data + shard training
[17:20:32]   shard data: building 130 shards
[17:21:27]   sessions split  train 1,117,419  val 166,155  test 319,137  -> 130 shards written
[17:21:57]   shard data done  85s
[17:22:02]   rolling graphs (window 3, target days 3-13) done  5s
[17:22:02]   training 130 shards on 4 GPU(s)
[17:22:02]   shards go to the next free GPU, largest first; lines below are the shards trained on GPU 0
[17:38:11]   shard 129  E35/50   813s  GPU0 #1, all 13/130
               train  MRR 0.2330  ACC@1 0.1520  ACC@5 0.3134  ACC@10 0.3937
               val    MRR 0.2072  ACC@1 0.1311  ACC@5 0.2811  ACC@10 0.3576
[17:44:27]   shard 128  E37/52   327s  GPU0 #2, all 20/130
               train  MRR 0.2496  ACC@1 0.1637  ACC@5 0.3353  ACC@10 0.4189
               val    MRR 0.1676  ACC@1 0.1036  ACC@5 0.2298  ACC@10 0.2946
[17:47:52]   shard 105  E44/59   171s  GPU0 #3, all 24/130
               train  MRR 0.2907  ACC@1 0.2005  ACC@5 0.3842  ACC@10 0.4669
               val    MRR 0.2091  ACC@1 0.1350  ACC@5 0.2844  ACC@10 0.3588
[17:51:38]   shard  87  E40/55   175s  GPU0 #4, all 31/130
               train  MRR 0.2871  ACC@1 0.1946  ACC@5 0.3822  ACC@10 0.4709
               val    MRR 0.1425  ACC@1 0.0870  ACC@5 0.1943  ACC@10 0.2485
[17:53:31]   shard  25  E28/43    91s  GPU0 #5, all 32/130
               train  MRR 0.2946  ACC@1 0.2014  ACC@5 0.3907  ACC@10 0.4784
               val    MRR 0.2026  ACC@1 0.1289  ACC@5 0.2799  ACC@10 0.3471
[17:56:00]   shard 126  E29/44   121s  GPU0 #6, all 38/130
               train  MRR 0.2683  ACC@1 0.1843  ACC@5 0.3559  ACC@10 0.4316
               val    MRR 0.1717  ACC@1 0.1088  ACC@5 0.2343  ACC@10 0.2944
[17:57:57]   shard  73  E35/50    93s  GPU0 #7, all 41/130
               train  MRR 0.3272  ACC@1 0.2299  ACC@5 0.4306  ACC@10 0.5205
               val    MRR 0.2166  ACC@1 0.1462  ACC@5 0.2880  ACC@10 0.3567
[17:59:12]   shard  27  E35/50    60s  GPU0 #8, all 44/130
               train  MRR 0.3334  ACC@1 0.2337  ACC@5 0.4420  ACC@10 0.5278
               val    MRR 0.2230  ACC@1 0.1426  ACC@5 0.3084  ACC@10 0.3819
[18:00:47]   shard  82  E25/40    73s  GPU0 #9, all 47/130
               train  MRR 0.2844  ACC@1 0.1940  ACC@5 0.3800  ACC@10 0.4621
               val    MRR 0.1970  ACC@1 0.1265  ACC@5 0.2684  ACC@10 0.3361
[18:02:32]   shard  26  E42/57    79s  GPU0 #10, all 52/130
               train  MRR 0.3602  ACC@1 0.2657  ACC@5 0.4593  ACC@10 0.5433
               val    MRR 0.1690  ACC@1 0.1172  ACC@5 0.2195  ACC@10 0.2732
[18:04:15]   shard 115  E41/56    84s  GPU0 #11, all 55/130
               train  MRR 0.3449  ACC@1 0.2457  ACC@5 0.4517  ACC@10 0.5369
               val    MRR 0.1633  ACC@1 0.1100  ACC@5 0.2238  ACC@10 0.2645
[18:06:27]   shard 116  E39/54   101s  GPU0 #12, all 61/130
               train  MRR 0.3206  ACC@1 0.2260  ACC@5 0.4210  ACC@10 0.5039
               val    MRR 0.1948  ACC@1 0.1263  ACC@5 0.2640  ACC@10 0.3300
[18:07:37]   shard 107  E42/57    53s  GPU0 #13, all 65/130
               train  MRR 0.3513  ACC@1 0.2541  ACC@5 0.4545  ACC@10 0.5353
               val    MRR 0.1934  ACC@1 0.1324  ACC@5 0.2563  ACC@10 0.3018
[18:08:27]   shard  60  E44/59    32s  GPU0 #14, all 67/130
               train  MRR 0.4170  ACC@1 0.2967  ACC@5 0.5559  ACC@10 0.6546
               val    MRR 0.1468  ACC@1 0.0959  ACC@5 0.1960  ACC@10 0.2486
[18:09:25]   shard  24  E34/49    40s  GPU0 #15, all 70/130
               train  MRR 0.3820  ACC@1 0.2850  ACC@5 0.4880  ACC@10 0.5660
               val    MRR 0.1921  ACC@1 0.1309  ACC@5 0.2512  ACC@10 0.3176
[18:10:59]   shard  36  E44/59    63s  GPU0 #16, all 75/130
               train  MRR 0.3134  ACC@1 0.2120  ACC@5 0.4183  ACC@10 0.5149
               val    MRR 0.1554  ACC@1 0.0974  ACC@5 0.2134  ACC@10 0.2681
[18:12:04]   shard  32  E44/59    38s  GPU0 #17, all 79/130
               train  MRR 0.4475  ACC@1 0.3418  ACC@5 0.5658  ACC@10 0.6445
               val    MRR 0.0878  ACC@1 0.0567  ACC@5 0.1201  ACC@10 0.1514
[18:13:31]   shard 113  E51/66    66s  GPU0 #18, all 83/130
               train  MRR 0.4027  ACC@1 0.2935  ACC@5 0.5183  ACC@10 0.6196
               val    MRR 0.0893  ACC@1 0.0587  ACC@5 0.1199  ACC@10 0.1435
[18:14:49]   shard  47  E65/80    54s  GPU0 #19, all 87/130
               train  MRR 0.4622  ACC@1 0.3442  ACC@5 0.5988  ACC@10 0.6899
               val    MRR 0.1118  ACC@1 0.0690  ACC@5 0.1536  ACC@10 0.1899
[18:15:53]   shard  28  E69/84    42s  GPU0 #20, all 91/130
               train  MRR 0.5862  ACC@1 0.4687  ACC@5 0.7288  ACC@10 0.8213
               val    MRR 0.0732  ACC@1 0.0459  ACC@5 0.1004  ACC@10 0.1268
[18:17:00]   shard  77  E41/56    46s  GPU0 #21, all 95/130
               train  MRR 0.3709  ACC@1 0.2644  ACC@5 0.4914  ACC@10 0.5777
               val    MRR 0.1280  ACC@1 0.0870  ACC@5 0.1733  ACC@10 0.2058
[18:17:52]   shard  41  E46/61    34s  GPU0 #22, all 101/130
               train  MRR 0.4251  ACC@1 0.3194  ACC@5 0.5477  ACC@10 0.6195
               val    MRR 0.1283  ACC@1 0.0872  ACC@5 0.1705  ACC@10 0.1964
[18:18:51]   shard  39  E56/71    38s  GPU0 #23, all 105/130
               train  MRR 0.4715  ACC@1 0.3489  ACC@5 0.6173  ACC@10 0.6989
               val    MRR 0.0735  ACC@1 0.0462  ACC@5 0.1039  ACC@10 0.1207
[18:19:44]   shard   5  E61/76    26s  GPU0 #24, all 108/130
               train  MRR 0.5954  ACC@1 0.4612  ACC@5 0.7711  ACC@10 0.8672
               val    MRR 0.0840  ACC@1 0.0548  ACC@5 0.1156  ACC@10 0.1424
[18:20:50]   shard  64  E42/57    38s  GPU0 #25, all 112/130
               train  MRR 0.3799  ACC@1 0.2639  ACC@5 0.5112  ACC@10 0.6203
               val    MRR 0.1097  ACC@1 0.0727  ACC@5 0.1453  ACC@10 0.1788
[18:21:18]   shard   8  E41/56    15s  GPU0 #26, all 115/130
               train  MRR 0.5856  ACC@1 0.4640  ACC@5 0.7445  ACC@10 0.8095
               val    MRR 0.0629  ACC@1 0.0468  ACC@5 0.0797  ACC@10 0.0878
[18:22:02]   shard  63  E72/87    24s  GPU0 #27, all 119/130
               train  MRR 0.6465  ACC@1 0.5071  ACC@5 0.8367  ACC@10 0.8999
               val    MRR 0.0606  ACC@1 0.0397  ACC@5 0.0873  ACC@10 0.0978
[18:23:03]   shard  12  E75/90    36s  GPU0 #28, all 124/130
               train  MRR 0.5232  ACC@1 0.3680  ACC@5 0.7243  ACC@10 0.8788
               val    MRR 0.0773  ACC@1 0.0508  ACC@5 0.1009  ACC@10 0.1242
[18:23:47]   shard  15  E59/74    20s  GPU0 #29, all 127/130
               train  MRR 0.5766  ACC@1 0.4217  ACC@5 0.7874  ACC@10 0.8965
               val    MRR 0.0646  ACC@1 0.0443  ACC@5 0.0936  ACC@10 0.1061
[18:24:11]   training done  130/130 shards  3729s
[18:24:11] STEP 3/3 shard routing evaluation (test)
[18:24:59]   test  MRR 0.2263 ACC@1 0.1501 ACC@5 0.3025 ACC@10 0.3744  routable 99.97%  48s
[18:24:59] done  4214s  -> Results/shard-runs/yjmob_14d/261027_15h51m07s_guts_k130_seed2026/results.json

## Unlearning

The node forget set removed from the GUTS run: only the affected shards are rebuilt from the clean data and retrained.

In [7]:
if not (SHARD_RUN_DIR / "results.json").exists():
    raise FileNotFoundError(f"{SHARD_RUN_DIR.relative_to(REPO_ROOT)} not finished: run the GUTS source run cell first")
if (UNLEARN_RUN_DIR / "results_unlearn.json").exists():
    print("finished run exists:", UNLEARN_RUN_DIR.relative_to(REPO_ROOT))
elif (UNLEARN_RUN_DIR / "unlearn_request.json").exists():
    unlearn_batch_retry.main(["--out_dir", str(UNLEARN_RUN_DIR), "--num_gpus", str(NUM_GPUS)])
else:
    unlearn_batch.main(["--state_dir", str(SHARD_RUN_DIR), "--forget_type", FORGET_TYPE,
                        "--forget_set_path", FORGET_SET, "--clean_source_dir", CLEAN_DIR,
                        "--num_gpus", str(NUM_GPUS), "--out_root", str(UNLEARN_RUN_DIR.parent),
                        "--run_name", UNLEARN_RUN_DIR.name])

[18:24:59] GUTS unlearn (node)  2026-10-27  source=Results/shard-runs/yjmob_14d/261027_15h51m07s_guts_k130_seed2026  out=Results/shard-unlearns/yjmob_14d/261027_15h51m07s_guts_k130_seed2026_node_0.05pct  GPUs=4
[18:25:36]   index: 130 shards, 4,033,798 train segments  37s
[18:25:36]   affected shards 108/130  (node: 14 records)
[18:25:37]   rebuilding 108 shards from the clean data (source partitions of days 0-13)
[18:26:33]   sessions split  train 1,117,071  val 166,104  test 319,064  -> 108 shards written
[18:27:03]   rebuild done (shard data + rolling graphs)  85s
[18:27:03]   retraining 108 shards on 4 GPU(s); shards go to the next free GPU, largest first; lines below are the shards trained on GPU 0
[18:43:03]   shard 129  E35/50   807s  GPU0 #1, all 13/108
               train  MRR 0.2331  ACC@1 0.1521  ACC@5 0.3131  ACC@10 0.3940
               val    MRR 0.2071  ACC@1 0.1311  ACC@5 0.2813  ACC@10 0.3576
[18:45:40]   shard  96  E33/48   132s  GPU0 #2, all 14/108
               train  MRR 0.2967  ACC@1 0.2074  ACC@5 0.3880  ACC@10 0.4714
               val    MRR 0.2659  ACC@1 0.1820  ACC@5 0.3578  ACC@10 0.4321
[18:48:29]   shard 100  E34/49   148s  GPU0 #3, all 18/108
               train  MRR 0.2995  ACC@1 0.2078  ACC@5 0.3937  ACC@10 0.4800
               val    MRR 0.2177  ACC@1 0.1426  ACC@5 0.2938  ACC@10 0.3715
[18:52:46]   shard  88  E28/43   213s  GPU0 #4, all 24/108
               train  MRR 0.2463  ACC@1 0.1664  ACC@5 0.3271  ACC@10 0.4020
               val    MRR 0.1947  ACC@1 0.1264  ACC@5 0.2619  ACC@10 0.3299
[18:54:36]   shard 110  E32/47    89s  GPU0 #5, all 28/108
               train  MRR 0.3487  ACC@1 0.2436  ACC@5 0.4606  ACC@10 0.5534
               val    MRR 0.3001  ACC@1 0.2056  ACC@5 0.3996  ACC@10 0.4889
[18:57:05]   shard 126  E29/44   121s  GPU0 #6, all 32/108
               train  MRR 0.2682  ACC@1 0.1842  ACC@5 0.3560  ACC@10 0.4315
               val    MRR 0.1716  ACC@1 0.1088  ACC@5 0.2326  ACC@10 0.2945
[19:00:30]   shard 122  E29/44   165s  GPU0 #7, all 38/108
               train  MRR 0.2710  ACC@1 0.1835  ACC@5 0.3614  ACC@10 0.4431
               val    MRR 0.2051  ACC@1 0.1332  ACC@5 0.2775  ACC@10 0.3448
[19:02:56]   shard 124  E48/63   120s  GPU0 #8, all 44/108
               train  MRR 0.3295  ACC@1 0.2307  ACC@5 0.4333  ACC@10 0.5254
               val    MRR 0.1197  ACC@1 0.0731  ACC@5 0.1676  ACC@10 0.2116
[19:05:38]   shard 120  E29/44   131s  GPU0 #9, all 50/108
               train  MRR 0.2713  ACC@1 0.1843  ACC@5 0.3615  ACC@10 0.4440
               val    MRR 0.1764  ACC@1 0.1140  ACC@5 0.2392  ACC@10 0.2998
[19:07:19]   shard 101  E60/75    72s  GPU0 #10, all 55/108
               train  MRR 0.4170  ACC@1 0.3117  ACC@5 0.5329  ACC@10 0.6213
               val    MRR 0.1269  ACC@1 0.0795  ACC@5 0.1760  ACC@10 0.2209
[19:08:17]   shard  24  E34/49    40s  GPU0 #11, all 59/108
               train  MRR 0.3821  ACC@1 0.2847  ACC@5 0.4887  ACC@10 0.5666
               val    MRR 0.1930  ACC@1 0.1323  ACC@5 0.2534  ACC@10 0.3145
[19:09:07]   shard  49  E45/60    33s  GPU0 #12, all 60/108
               train  MRR 0.4586  ACC@1 0.3452  ACC@5 0.5896  ACC@10 0.6721
               val    MRR 0.1354  ACC@1 0.0926  ACC@5 0.1860  ACC@10 0.2096
[19:10:28]   shard  16  E36/51    57s  GPU0 #13, all 64/108
               train  MRR 0.3263  ACC@1 0.2304  ACC@5 0.4287  ACC@10 0.5128
               val    MRR 0.1454  ACC@1 0.0902  ACC@5 0.1955  ACC@10 0.2553
[19:11:34]   shard  52  E39/54    49s  GPU0 #14, all 68/108
               train  MRR 0.3785  ACC@1 0.2726  ACC@5 0.4929  ACC@10 0.5845
               val    MRR 0.1950  ACC@1 0.1286  ACC@5 0.2580  ACC@10 0.3251
[19:12:48]   shard  21  E68/83    46s  GPU0 #15, all 72/108
               train  MRR 0.4235  ACC@1 0.3017  ACC@5 0.5700  ACC@10 0.6720
               val    MRR 0.0837  ACC@1 0.0506  ACC@5 0.1148  ACC@10 0.1456
[19:14:04]   shard  28  E100/100    50s  GPU0 #16, all 77/108
               train  MRR 0.6479  ACC@1 0.5396  ACC@5 0.7813  ACC@10 0.8773
               val    MRR 0.0733  ACC@1 0.0432  ACC@5 0.1031  ACC@10 0.1315
[19:14:34]   shard   0  E37/52    16s  GPU0 #17, all 80/108
               train  MRR 0.4587  ACC@1 0.3662  ACC@5 0.5679  ACC@10 0.6268
               val    MRR 0.0770  ACC@1 0.0482  ACC@5 0.1130  ACC@10 0.1250
[19:15:00]   shard   7  E31/46    14s  GPU0 #18, all 82/108
               train  MRR 0.4251  ACC@1 0.3399  ACC@5 0.5208  ACC@10 0.5820
               val    MRR 0.0634  ACC@1 0.0458  ACC@5 0.0840  ACC@10 0.0942
[19:16:09]   shard  39  E67/82    44s  GPU0 #19, all 86/108
               train  MRR 0.5081  ACC@1 0.3819  ACC@5 0.6585  ACC@10 0.7442
               val    MRR 0.0739  ACC@1 0.0467  ACC@5 0.1057  ACC@10 0.1216
[19:17:09]   shard 106  E50/65    37s  GPU0 #20, all 91/108
               train  MRR 0.4137  ACC@1 0.2876  ACC@5 0.5582  ACC@10 0.6801
               val    MRR 0.0925  ACC@1 0.0573  ACC@5 0.1268  ACC@10 0.1662
[19:18:01]   shard  14  E87/100    24s  GPU0 #21, all 94/108
               train  MRR 0.7548  ACC@1 0.6295  ACC@5 0.9267  ACC@10 0.9874
               val    MRR 0.0375  ACC@1 0.0278  ACC@5 0.0486  ACC@10 0.0545
[19:18:40]   shard  58  E54/69    19s  GPU0 #22, all 98/108
               train  MRR 0.6715  ACC@1 0.5366  ACC@5 0.8558  ACC@10 0.9344
               val    MRR 0.0470  ACC@1 0.0288  ACC@5 0.0715  ACC@10 0.0796
[19:19:36]   shard 119  E47/62    32s  GPU0 #23, all 103/108
               train  MRR 0.3849  ACC@1 0.2554  ACC@5 0.5301  ACC@10 0.6642
               val    MRR 0.0842  ACC@1 0.0537  ACC@5 0.1194  ACC@10 0.1449
[19:20:20]   shard  15  E59/74    20s  GPU0 #24, all 107/108
               train  MRR 0.5751  ACC@1 0.4192  ACC@5 0.7847  ACC@10 0.8926
               val    MRR 0.0655  ACC@1 0.0452  ACC@5 0.0947  ACC@10 0.1052
[19:20:22]   retraining done  108/108 shards  3199s
[19:20:22] shard routing evaluation (test)
[19:21:09]   test  MRR 0.2258 ACC@1 0.1496 ACC@5 0.3020 ACC@10 0.3739  routable 99.97%  48s
[19:21:09] done  3370s  -> Results/shard-unlearns/yjmob_14d/261027_15h51m07s_guts_k130_seed2026_node_0.05pct/results_unlearn.json

## Results

Prediction metrics of the three runs on the routable test transitions and the partition quality of the GUTS run
after boundary refinement (mean over the 14 days).

In [10]:
def load_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)

base = load_json(BASE_RUN_DIR / "results.json")
shard = load_json(SHARD_RUN_DIR / "results.json")
unlearn = load_json(UNLEARN_RUN_DIR / "results_unlearn.json")
K = shard["partition"]["num_shards"]

evals = {
    "Full-Graph": base["graphsage_agg_eval"],
    f"GUTS (K={K})": shard["graphsage_agg_eval"],
    f"GUTS unlearn ({FORGET_TYPE} {FORGET_PERCENT:g}%)": unlearn["eval"],
}
prediction = pd.DataFrame([{
    "MRR": ev["routable"]["mrr"], "ACC@1": ev["routable"]["acc@1"],
    "ACC@5": ev["routable"]["acc@5"], "ACC@10": ev["routable"]["acc@10"]
} for ev in evals.values()], index=list(evals))
display(prediction.round(4))

tb, ts, tu = base["timing_ms"], shard["timing_ms"], unlearn["timing_ms"]
timing = pd.Series({
    "Full-Graph: training (s)": tb["train"] / 1000,
    "Full-Graph: wall time (min)": base["wall_time_s"] / 60,
    "GUTS: partition, 14 days (s)": ts["partition"] / 1000,
    "GUTS: train per shard, mean (s)": ts["per_shard_train"]["mean"] / 1000,
    "GUTS: wall time (min)": shard["wall_time_s"] / 60,
    "Unlearn: affected shards": f"{len(unlearn['forget_request']['affected_shards'])}/{K}",
    "Unlearn: retraining (s)": tu["retrain_wall_s"],
    "Unlearn: wall time (min)": unlearn["wall_time_s"] / 60,
}, name="time")
display(timing.to_frame())

                              MRR   ACC@1   ACC@5  ACC@10
Full-Graph                 0.2480  0.1645  0.3315  0.4131
GUTS (K=130)               0.2263  0.1501  0.3025  0.3744
GUTS unlearn (node 0.05%)  0.2258  0.1496  0.3020  0.3739

                                      time
Full-Graph: training (s)          4389.051
Full-Graph: wall time (min)         83.615
GUTS: partition, 14 days (s)       295.879
GUTS: train per shard, mean (s)  87.237462
GUTS: wall time (min)            70.241667
Unlearn: affected shards           108/130
Unlearn: retraining (s)             3078.1
Unlearn: wall time (min)         56.173333